# Generated by Django 4.2.21 on 2025-05-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_of_corruption', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='act',
            name='corruption_form',
            field=models.ManyToManyField(related_name='acts', to='app.corruptionform'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='corruption_form',
            field=models.ManyToManyField(related_name='factors', to='app.corruptionform'),
        ),
    ]
