# Generated by Django 4.2.21 on 2025-05-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_incident_alter_act_corruption_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='interplay',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
