# Generated by Django 4.2.21 on 2025-06-03 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_act_interplay_alter_act_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='act',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='act', to='app.act'),
        ),
        migrations.AlterField(
            model_name='act',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
