# Generated by Django 4.2.21 on 2025-06-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_act_alter_act_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback_type', models.SmallIntegerField(choices=[(0, 'Bug Report'), (1, 'Feature Request'), (2, 'General Feedback'), (3, 'Compliment'), (4, 'Complaint')], default=2)),
                ('message', models.TextField()),
            ],
        ),
    ]
