# Generated by Django 4.2.21 on 2025-06-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
