# Generated by Django 4.2.21 on 2025-06-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_act_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='indicators',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
