# Generated by Django 4.2.21 on 2025-06-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_factor_indicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorruptionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(default='Corruption is receiving, asking for or giving any gratification to induce a person to do a favour with a corrupt intent.')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Corruption page',
                'verbose_name_plural': 'Corruption page',
            },
        ),
    ]
