# Generated by Django 4.2.21 on 2025-06-23 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_corruptionpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('factors', models.CharField(blank=True, max_length=3000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_interplay', to='app.act')),
                ('corruption_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interplay', to='app.corruptionform')),
            ],
            options={
                'verbose_name_plural': 'Interplay',
            },
        ),
    ]
