# Generated by Django 4.2.21 on 2025-06-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_interplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='interplay',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='interplay',
            name='corruption_form',
        ),
        migrations.AddField(
            model_name='interplay',
            name='corruption_form',
            field=models.ManyToManyField(related_name='interplay', to='app.corruptionform'),
        ),
    ]
