# Generated by Django 4.2.21 on 2025-06-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_interplay_references_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interplay',
            name='corruption_form',
        ),
    ]
