# Generated by Django 4.2.21 on 2025-07-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_interplaycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptionpage',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
