# Generated by Django 5.2.8 on 2025-12-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_employeeresponse_publicresponse_systemresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeresponse',
            name='org_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='10. Organization Name'),
        ),
        migrations.AddField(
            model_name='publicresponse',
            name='org_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='10. Organization Name'),
        ),
        migrations.AlterField(
            model_name='employeeresponse',
            name='org_age',
            field=models.IntegerField(choices=[(1, '0-4'), (2, '5-9'), (3, '10-14'), (4, '15-19'), (5, '20+')], verbose_name='12. Organization age (in years)'),
        ),
        migrations.AlterField(
            model_name='employeeresponse',
            name='org_category',
            field=models.CharField(max_length=200, verbose_name='11. Organization Category (eg Education, security, Judiciary etc)'),
        ),
        migrations.AlterField(
            model_name='employeeresponse',
            name='org_location',
            field=models.IntegerField(choices=[(1, 'Northern'), (2, 'Western'), (3, 'Eastern'), (4, 'Central')], verbose_name='14. Organization Location'),
        ),
        migrations.AlterField(
            model_name='employeeresponse',
            name='org_size',
            field=models.IntegerField(choices=[(1, '<10'), (2, '10-49'), (3, '50-99'), (4, '100+')], verbose_name='13. Organization size (No of employees)'),
        ),
        migrations.AlterField(
            model_name='publicresponse',
            name='org_age',
            field=models.IntegerField(choices=[(1, '0-4'), (2, '5-9'), (3, '10-14'), (4, '15-19'), (5, '20+')], verbose_name='12. Organization age (in years)'),
        ),
        migrations.AlterField(
            model_name='publicresponse',
            name='org_category',
            field=models.CharField(max_length=200, verbose_name='11. Organization Category (eg Education, security, Judiciary, local government etc)'),
        ),
        migrations.AlterField(
            model_name='publicresponse',
            name='org_location',
            field=models.IntegerField(choices=[(1, 'Northern'), (2, 'Western'), (3, 'Eastern'), (4, 'Central')], verbose_name='14. Organization Location'),
        ),
        migrations.AlterField(
            model_name='publicresponse',
            name='org_size',
            field=models.IntegerField(choices=[(1, '<10'), (2, '10-49'), (3, '50-99'), (4, '100+')], verbose_name='13. Organization size (No of employees)'),
        ),
    ]
