"""
Django settings for corruption_lens project.

Generated by 'django-admin startproject' using Django 3.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

import environ

env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')9&j52$60d=il%c3b8ju6a6$w+@si$!wgtizqgel!uj5h_0xj3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['f0d5-41-210-147-206.ngrok-free.app']
ALLOWED_HOSTS = ['*', 'localhost', '127.0.0.1', '.ngrok-free.app']
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',  # Allows any ngrok subdomain
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

INSTALLED_APPS += [
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'corruption_lens.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, 'templates/')],
#         # 'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#             'loaders': [
#                 'admin_tools.template_loaders.Loader',
#                 'django.template.loaders.filesystem.Loader',
#                 'django.template.loaders.app_directories.Loader'
#             ]
#         },
#     },
# ]

WSGI_APPLICATION = 'corruption_lens.wsgi.application'
# FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': env('DATABASE_ENGINE'),
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASSWORD'),
        'HOST': env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Kampala'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

MEDIA_ROOT = os.path.join(BASE_DIR, 'image_files/')
MEDIA_URL = '/image_files/'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

JAZZMIN_SETTINGS = {
    # ... your existing settings (logo, theme, etc.) ...

    # This creates the order of sections in the sidebar
    "order_with_respect_to": [
        "Core Content",           # ← your Acts, Factors, Forms, etc.
        "Questionnaires",         # ← This will be your dedicated section
        "User Submissions",       # ← Incidents, Feedback, Comments
        "Authentication",         # ← auth.User, auth.Group (optional)
    ],

    # Optional: Nice icons for each section
    "icons": {
        # Your questionnaire models
        "app.SystemResponse": "fas fa-clipboard-list",
        "app.PublicResponse": "fas fa-users",
        "app.EmployeeResponse": "fas fa-briefcase",

        # Other models (example)
        "app.Act": "fas fa-gavel",
        "app.Factor": "fas fa-puzzle-piece",
        "app.CorruptionForm": "fas fa-file-alt",
        "app.Incident": "fas fa-exclamation-triangle",
        "app.Feedback": "fas fa-comment-dots",

        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users-cog",
    },

    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file-alt",

    # Show the UI builder so you can tweak colors live
    "show_ui_builder": True,
}

ADMIN_REORDER = (
    # Reorder apps (or use custom section names as "apps")
    'app',  # Replace with your actual app name (e.g., 'corruption')
    'auth',      # Built-in users/groups

    # Custom sections/groups (use strings like app names)
    'Core Content',
    'Questionnaires',
    'User Submissions',
)

# Models within each "app" or section (list them in order)
ADMIN_REORDER_MODELS = {
    'app': [  # Your main app
        'CorruptionForm',
        'Factor',
        'Act',
        'Comment',
        'Incident',
        'Interplay',
        'InterplayComment',
        'Feedback',
    ],
    'Core Content': [  # Virtual group for core models (pull from your_app)
        {'model': 'app.corruptionform', 'label': 'Corruption Forms'},
        {'model': 'app.factor', 'label': 'Factors'},
        {'model': 'app.act', 'label': 'Acts'},
    ],
    'Questionnaires': [  # ← Your dedicated section!
        {'model': 'app.systemresponse', 'label': 'System Responses'},
        {'model': 'app.publicresponse', 'label': 'Public Responses'},
        {'model': 'app.employeeresponse', 'label': 'Employee Responses'},
    ],
    'User Submissions': [
        {'model': 'app.comment', 'label': 'Comments'},
        {'model': 'app.incident', 'label': 'Incidents'},
        {'model': 'app.feedback', 'label': 'Feedback'},
    ],
    'auth': [
        'User',
        'Group',
    ],
}

# # Optional: Rename app/section labels
# ADMIN_REORDER_APP_LABELS = {
#     'your_app': 'Corruption Data',
#     'auth': 'Authentication',
# }

# # Optional: Exclude models (they still accessible via URL)
# ADMIN_REORDER_EXCLUDE = (
#     # ('your_app', 'SomePrivateModel'),  # Uncomment to hide
# )